# Source: https://docs.docker.com/engine/install/ubuntu/
- name: Install Docker Dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
    state: present

- name: Install Python SDK
  become: true
  pip:
    executable: pip3
    name:
      - docker
      - docker-compose
    state: present

- name: Install Docker GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Add Docker APT Repository
  become: true
  apt_repository:
    repo: "{{ 'deb [arch=amd64] https://download.docker.com/linux/ubuntu ' + ubuntu_codename + ' stable' }}"
    filename: docker-ce
    state: present

- name: Install Docker
  become: true
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
