- name: Ensure Traefik config path exists
  become: true
  file:
    path: "/etc/traefik"
    state: directory

- name: Install Traefik config
  become: true
  template:
    src: "{{ role_path }}/templates/traefik.yml.j2"
    dest: /etc/traefik/traefik.yml
    owner: root
    group: root
    mode: '0640'
  register: traefik_config

- name: Create Gateway network
  become: true
  community.docker.docker_network:
    name: gateway
    attachable: true
    state: present

- name: Start Traefik
  become: true
  community.docker.docker_compose:
    project_name: traefik
    remove_orphans: true
    recreate: "{{ 'always' if traefik_config.changed else 'smart' }}"
    definition:
      version: '3.3'
      services:
        traefik:
          image: "traefik:v2.7"
          container_name: "traefik"
          restart: unless-stopped
          labels:
            - 'com.centurylinklabs.watchtower.enable="true"'
          ports:
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/traefik/:/etc/traefik/"
          networks:
            - default
      networks:
        default:
          external:
            name: gateway
